# conda environment description file for docs build environment
# on readthedocs.org

name: sphinx-build

channels:
  - defaults
  - gomss-nowcast

dependencies:
  - matplotlib
  - nemo_nowcast
  - python=3.6
