# conda environment description file for SalishSeaNowcast package
# production deployment environment
#
# Create a conda environment for production deployment
# of the Salish Sea Nowcast system with:
#
#    $ conda env create -f SalishSeaNowcast/environment-prod.yaml
#    $ source activate nowcast-env
#    $ pip install --editable NEMO_Nowcast/
#    $ pip install --editable moad_tools/
#    $ pip install --editable tools/SalishSeaTools/
#    $ pip install --editable OPPTools/
#    $ pip install --editable NEMO-Cmd/
#    $ pip install --editable SalishSeaCmd/
#    $ pip install --editable FVCOM-Cmd/
#    $ pip install --editable SalishSeaNowcast/

name: nowcast-env

channels:
  - gomss-nowcast
  - conda-forge
  - defaults

dependencies:
  - arrow
  - basemap
  - beautifulsoup4
  - bottleneck
  - circus
  - cliff
  - cmocean
  - dask
  - docutils
  - gsw
  - lxml
  - mako
  - matplotlib>=3
  - netcdf4
  - numpy
  - pandas
  - paramiko
  - pillow
  - pip
  - poppler
  - pygrib
  - pyproj
  - pypdf2
  - pytables
  - python=3.7
  - pyyaml
  - pyzmq
  - requests
  - scipy
  - shapely
  - watchdog
  - xarray

  - pip:
    - angles
    - attrs
    - driftwood
    - f90nml
    - feedgen
    - python-hglib
    - raven
    - retrying
    - schedule
    - scour
    - utm
    - zeep
