# conda environment description file for docs build environment
# on readthedocs.org

name: sphinx-build

channels:
  - defaults
  - gomss-nowcast

dependencies:
  - matplotlib
  - nemo_nowcast
  - python=3.5
  - pip:
    - sphinx==1.5.4
    - sphinx_rtd_theme==0.2.5b1
