# conda environment description file for SalishSeaNowcast package
# development environment
#
# Create a conda environment for development, testing, and documentation
# of the Salish Sea Nowcast system with:
#
#    $ conda env create -f SalishSeaNowcast/environment-dev.yaml
#    $ source activate salishsea-nowcast
#    $ pip install --editable NEMO_Nowcast/
#    $ pip install --editable moad_tools/
#    $ pip install --editable tools/SalishSeaTools/
#    $ pip install --editable OPPTools/
#    $ pip install --editable NEMO-Cmd/
#    $ pip install --editable SalishSeaCmd/
#    $ pip install --editable FVCOM-Cmd/
#    $ pip install --editable SalishSeaNowcast/

name: salishsea-nowcast

channels:
  - conda-forge
  - defaults
  - gomss-nowcast

dependencies:
  - arrow
  - basemap
  - beautifulsoup4
  - bottleneck
  - cliff
  - cmocean
  - coloredlogs
  - dask
  - docutils
  - gsw
  - lxml
  - mako
  - matplotlib>=3
  - netcdf4
  - numpy
  - pandas
  - paramiko
  - pillow
  - pip
  - poppler
  - pygrib
  - pypdf2
  - pyproj
  - pytables
  - python=3.7
  - pyyaml
  - pyzmq
  - requests
  - scipy
  - shapely
  - supervisor
  - verboselogs
  - watchdog
  - xarray

  # For coding style
  - black

  # For unit tests
  - coverage
  - pytest

  # For documentation
  - sphinx
  - sphinx_rtd_theme

  # For exploration
#  - ipython
#  - jupyter

  - pip:
    - angles
    - attrs
    - f90nml
    - feedgen
    - python-hglib
    - retrying
    - schedule
    - scour
    - utm
    - zeep

    # For unit tests
    - pytest-randomly

    # For exception monitoring
    - raven
