# conda environment description file for SalishSeaNowcast package
# production deployment environment
#
# Create a conda environment for production deployment
# of the Salish Sea Nowcast system with:
#
#    $ conda env create -f SalishSeaNowcast/environment-prod.yaml
#    $ source activate nowcast-env
#    $ pip install --editable NEMO_Nowcast/
#    $ pip install --editable SalishSeaTools/
#    $ pip install --editable SalishSeaCmd/
#    $ pip install --editable SalishSeaNowcast/

name: nowcast-env

channels:
  - gomss-nowcast
  - defaults
  - conda-forge

dependencies:
  - beautifulsoup4
  - bottleneck
  - cliff
  - matplotlib
  - nemo_nowcast
  - netcdf4
  - numpy
  - pandas
  - paramiko
  - pillow
  - pip
  - python=3
  - retrying
  - scipy
  - xarray

  - pip:
    - angles
    - driftwood
    - raven
