# conda environment description file for SalishSeaNowcast package
# development environment
#
# Create a conda environment for development, testing, and documentation
# of the Salish Sea Nowcast system with:
#
#    $ conda env create -f SalishSeaNowcast/environment-prod.yaml
#    $ source activate nowcast
#    $ pip install --editable NEMO_Nowcast/
#    $ pip install --editable SalishSeaNowcast/

name: nowcast

channels:
  - gomss-nowcast
  - conda-forge
  - defaults

dependencies:
  - arrow
  - attrs
  - circus
  - pyyaml
  - pyzmq
  - pip
  - python=3
  - requests
  - schedule

  # For unit tests
#  - coverage
#  - pytest

  # For documentation
#  - sphinx

  # For exploration
#  - ipython
#  - jupyter

  - pip:
    - raven
