# conda environment description file for SalishSeaNowcast package
# production deployment environment
#
# Create a conda environment for production deployment
# of the Salish Sea Nowcast system with:
#
#    $ conda env create -f SalishSeaNowcast/environment-prod.yaml
#    $ source activate nowcast
#    $ pip install --editable SalishSeaNowcast/

name: nowcast-env

channels:
  - gomss-nowcast
  - defaults
  - conda-forge

dependencies:
  - matplolib
  - nemo_nowcast
  - netcdf4
  - numpy
  - paramiko
  - pip
  - python=3

  - pip:
    - driftwood
    - raven
