# conda environment description file for SalishSeaNowcast package
# production deployment environment
#
# Create a conda environment for production deployment
# of the Salish Sea Nowcast system with:
#
#    $ cd tools
#    $ conda env create -f SalishSeaNowcast/environment-prod.yaml
#    $ source activate nowcast
#    $ pip install --editable SalishSeaTools/
#    $ pip install --editable SalishSeaCmd/
#    $ pip install --editable SalishSeaNowcast/

name: nowcast-env
dependencies:
- bottleneck
- lxml
- mako
- matplotlib
- netCDF4
- numpy
- pandas
- paramiko
- pillow
- pyyaml
- pyzmq
- pip
- python=3
- requests
- scipy
- sphinx
- xarray
- pip:
  - angles
  - arrow
  - BeautifulSoup4
  - driftwood
  - feedgen
  - retrying
  - sphinx-bootstrap-theme
