# conda environment description file for SalishSeaNowcast package
# development environment
#
# Create a conda environment for development, testing, and documentation
# of the Salish Sea Nowcast system with:
#
#    $ conda env create -f SalishSeaNowcast/environment-prod.yaml
#    $ source activate salishsea-nowcast
#    $ pip install --editable NEMO_Nowcast/
#    $ pip install --editable SalishSeaTools/
#    $ pip install --editable SalishSeaCmd/
#    $ pip install --editable SalishSeaNowcast/

name: salishsea-nowcast

channels:
  - gomss-nowcast
  - defaults
  - conda-forge

dependencies:
  - arrow
  - attrs
  - beautifulsoup4
  - bottleneck
  - circus
  - cliff
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - paramiko
  - pillow
  - pyyaml
  - pyzmq
  - pip
  - python=3
  - requests
  - retrying
  - schedule
  - scipy
  - xarray

  # For unit tests
  - coverage
  - pytest

  # For documentation
  - sphinx

  # For exploration
#  - ipython
#  - jupyter

  - pip:
    - angles
    - driftwood

    # For exception monitoring
    - raven

    # For documentation
    - sphinx-rtd-theme
