# conda environment description file for SalishSeaNowcast package
# development environment
#
# Create a conda environment for development, testing, and documentation
# of the Salish Sea Nowcast system with:
#
#    $ conda env create -f SalishSeaNowcast/environment-dev.yaml
#    $ source activate salishsea-nowcast
#    $ pip install --editable NEMO_Nowcast/
#    $ pip install --editable tools/SalishSeaTools/
#    $ pip install --editable OPPTools/
#    $ pip install --editable NEMO-Cmd/
#    $ pip install --editable SalishSeaCmd/
#    $ pip install --editable FVCOM-Cmd/
#    $ pip install --editable SalishSeaNowcast/

name: salishsea-nowcast

channels:
  - gomss-nowcast
  - conda-forge
  - defaults

dependencies:
  - arrow
  - attrs
  - basemap
  - beautifulsoup4
  - bottleneck
  - circus
  - cliff
  - cmocean
  - dask
  - docutils
  - lxml
  - mako
  - matplotlib=1.5.3
  - netcdf4
  - numpy
  - pandas
  - paramiko
  - pillow
  - pip
  - pygrib
  - python=3.6
  - pyyaml
  - pyzmq
  - requests
  - schedule
  - scipy
  - xarray

  # For unit tests
  - coverage
  - pytest

  # For documentation
  - sphinx
  - sphinx_rtd_theme

  # For exploration
#  - ipython
#  - jupyter

  - pip:
    - angles
    - driftwood
    - f90nml
    - feedgen
    - python-hglib
    - retrying
    - scour
    - utm
    - zeep

    # For exception monitoring
    - raven

    # For coding style
    - yapf
