# conda environment description file for docs build envioronment
# on readthedocs.org

name: sphinx-build

channels:
  - defaults
  - gomss-nowcast

dependencies:
  - beautifulsoup4
  - mako
  - matplotlib
  - nemo_nowcast
  - netcdf4
  - numpy
  - pandas
  - paramiko
  - python=3
  - scipy

  - pip:
    - driftwood
