# conda environment description file for SalishSeaNowcast package
# development environment
#
# Create a conda environment for development, testing, and documentation
# of the Salish Sea Nowcast system with:
#
#    $ conda env create -f SalishSeaNowcast/environment-prod.yaml
#    $ source activate nowcast
#    $ pip install --editable tools/SalishSeaTools/
#    $ pip install --editable tools/SalishSeaCmd/
#    $ pip install --editable SalishSeaNowcast/

name: nowcast
dependencies:
- bottleneck
- coverage
- ipython
- jupyter
- lxml
- mako
- matplotlib
- netCDF4
- numpy
- pandas
- paramiko
- pillow
- pytest
- pyyaml
- pyzmq
- pip
- python=3
- requests
- scipy
- sphinx
- xarray
- pip:
  - angles
  - arrow
  - BeautifulSoup4
  - driftwood
  - feedgen
  - ipdb
  - nbsphinx
  - retrying
  - sphinx-bootstrap-theme
