# conda environment description file for docs build envioronment
# on readthedocs.org

name: sphinx-build

dependencies:
- bottleneck
- h5py
- ipython
- lxml
- mako
- matplotlib
- netCDF4
- numpy
- pandas
- paramiko
- pillow
- pip
- python=3
- pytz
- pyyaml
- pyzmq
- requests
- scipy
- sphinx
- xarray
- pip:
  - angles
  - arrow
  - BeautifulSoup4
  - cliff
  - driftwood
  - feedgen
  - nbsphinx
  - retrying
  - sphinx-bootstrap-theme
