# `reshapr extract` config to resample v202111 hour-average physics tracers to day-average

dataset:
  model profile: SalishSeaCast-202111-salish.yaml
  time base: hour
  variables group: physics tracers

dask cluster: tcp://142.103.36.12:4386

# Placeholder state/end dates that are overridden by worker's run-date arg
start date: 2007-01-01
end date: 2007-01-01

extract variables:
  - sossheig
  - vosaline
  - votemper
  - sigma_theta
  - e3t

resample:
  time interval: 1D
  aggregation: mean

extracted dataset:
  name: SalishSeaCast_1d_grid_T
  description: Day-averaged physics tracers variables resampled from v202111 SalishSea_1h_*_grid_T.nc
  use model coords: True
  deflate: True
  format: NETCDF4
  # ddmmmyy/ directory will be appended to dest dir by worker
  dest dir: /results2/SalishSea/nowcast-green.202111/
