# Logging system configuration for circus process manager

version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s %(levelname)s [%(name)s] %(message)s'
handlers:
  logfile:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: /SalishSeaCast/logs/nowcast/circus.log
    maxBytes: 100000
    backupCount: 3
  sentry:
    class: raven.handlers.logging.SentryHandler
    level: ERROR
    # dsn will be obtained from SENTRY_DSN environment variable
root:
  level: DEBUG
  handlers:
   - logfile
   - sentry
