# System configuration file for Salish Sea Nowcast system

# System status checklist file
checklist file: $(NOWCAST.ENV.NOWCAST_LOGS)/nowcast_checklist.yaml

# Python interpreter in environment with all dependencies installed
python: $(NOWCAST.ENV.NOWCAST_ENV)/bin/python

# Filesystem group name to use for ownership of newly created files
file group: sallen


# Workers scheduled to run at specific times
scheduled workers:
  # Worker module name (fully qualified, dotted notation)
  nowcast.workers.download_weather:
    # Time period for worker launch repetition
    every: day
    # Time at which to launch the worker
    # (quotes are required to ensure that time is interpreted as a string)
    at: '05:00'
    # Optional command-line options for the worker
    # (quotes are necessary to force interpretation as a string)
    cmd line opts: '06'
  nowcast.workers.download_weather:
    every: day
    at: '11:00'
    cmd line opts: '12'
  nowcast.workers.download_weather:
    every: day
    at: '17:00'
    cmd line opts: '18'
  nowcast.workers.download_weather:
    every: day
    at: '23:00'
    cmd line opts: '00'


coordinates: /results/nowcast-sys/NEMO-forcing/grid/coordinates_seagrid_SalishSea.nc


weather:
  # Destination directory for downloaded GEM 2.5km operational model GRIB2 files
  GRIB dir: /results/forcing/atmospheric/GEM2.5/GRIB/
  # Location of wgrib2 executable
  wgrib2: /results/nowcast-sys/private-tools/grib2/wgrib2/wgrib2
  # Location of Pramod Thupaki's grid_defn.pl script
  grid_defn.pl: /results/nowcast-sys/private-tools/PThupaki/grid_defn.pl
  # Destination directory for NEMO forcing files generated from GRIB2 files
  ops dir: /results/forcing/atmospheric/GEM2.5/operational/


rivers:
  # File containing daily average Fraser river flow at Hope
  ECget Fraser flow: /data/dlatorne/SOG-projects/SOG-forcing/ECget/Fraser_flow
  # Monthly climatology
  monthly climatology: /results/nowcast-sys/NEMO-forcing/rivers/rivers_month.nc
  # File that describes Fraser River climatology separation from measured
  # flow at Hope
  Fraser climatology: /results/nowcast-sys/tools/I_ForcingFiles/Rivers/FraserClimatologySeparation.yaml
  # Destination directory for river runoff forcing file
  rivers_dir: /results/forcing/rivers/


ssh:
  # Directory containing tidal predication file for sea surface height correction
  tidal_predictions: /results/nowcast-sys/tools/SalishSeaNowcast/tidal_predictions/
  # Destination directory for Neah Bay sea surface height open boundary files
  ssh_dir: /results/forcing/sshNeahBay/


run types:
  # Keys are run types to execute, values are NEMO configuration name,
  # bathymetry, and mesh mask to use.
  # Note that forecast requires a nowcast to have been completed,
  # and forecast2 requires a forecast to have been completed.
  nowcast:
    config name: SalishSea
    bathymetry: /results/nowcast-sys/NEMO-forcing/grid/bathy_meter_SalishSea2.nc
    mesh mask: /results/nowcast-sys/NEMO-forcing/grid/mesh_mask_SalishSea2.nc
  nowcast-green:
    config name:  SOG
    bathymetry: /results/nowcast-sys/NEMO-forcing/grid/bathy_downonegrid2.nc
    mesh mask: /results/nowcast-sys/NEMO-forcing/grid/mesh_mask_downbyone2.nc
  forecast:
    config name:  SalishSea
    bathymetry: /results/nowcast-sys/NEMO-forcing/grid/bathy_meter_SalishSea2.nc
    mesh mask: /results/nowcast-sys/NEMO-forcing/grid/mesh_mask_SalishSea2.nc
  forecast2:
    config name:  SalishSea
    bathymetry: /results/nowcast-sys/NEMO-forcing/grid/bathy_meter_SalishSea2.nc
    mesh mask: /results/nowcast-sys/NEMO-forcing/grid/mesh_mask_SalishSea2.nc


run:
  results archive:
    nowcast: /results/SalishSea/nowcast/
    forecast: /results/SalishSea/forecast/
    forecast2: /results/SalishSea/forecast2/
    nowcast-green: /results/SalishSea/nowcast-green/


# Logging system configuration
logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    simple:
      format: '%(asctime)s %(levelname)s [%(name)s] %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      # Level 100 disables console logging.
      # Use worker --debug flag to enable console logging.
      level: 100
      formatter: simple
      stream: ext://sys.stdout
    info_text:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: simple
      filename: $(NOWCAST.ENV.NOWCAST_LOGS)/nowcast.log
      backupCount: 7
    debug_text:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: simple
      filename: $(NOWCAST.ENV.NOWCAST_LOGS)/nowcast.debug.log
      backupCount: 7
    checklist:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: simple
      filename: $(NOWCAST.ENV.NOWCAST_LOGS)/checklist.log
      backupCount: 7
    sentry:
      class: raven.handlers.logging.SentryHandler
      level: ERROR
      # dsn will be obtained from SENTRY_DSN environment variable
    wgrib2_text:
      class: logging.FileHandler
      level: DEBUG
      formatter: simple
      filename: $(NOWCAST.ENV.NOWCAST_LOGS)/wgrib2.log
      mode: w
    get_NeahBay_ssh_png:
      # **NOTE:** This isn't a handler for Python logging, rather it is a
      # convenient and logical place to define the storage location for the
      # image file that the get_NeahBay_ssh worker generates
      class: logging.FileHandler  # irrevelant
      level: DEBUG  # irrevelant, but accurate
      formatter: simple  # irrevelant
      filename: $(NOWCAST.ENV.NOWCAST_LOGS)/NBssh.png  # THE IMPORTANT BIT!!
      mode: w  # irrevelant, but accurate
    grib_to_netcdf_png:
      # **NOTE:** This isn't a handler for Python logging, rather it is a
      # convenient and logical place to define the storage location for the
      # image file that the grib_to_netcdf worker generates
      class: logging.FileHandler  # irrevelant
      level: DEBUG  # irrevelant, but accurate
      formatter: simple  # irrevelant
      filename: $(NOWCAST.ENV.NOWCAST_LOGS)/wg.png  # THE IMPORTANT BIT!!
      mode: w  # irrevelant, but accurate
  loggers:
    wgrib2:
      qualname: wgrib2
      level: DEBUG
      propagate: False
      handlers:
        - wgrib2_text
  root:
    level: DEBUG
    handlers:
     - console
     - info_text
     - debug_text
     - sentry


# Message system
zmq:
  server: localhost
  ports:
    # traffic between manager and message broker
    manager: 4343
    # traffic between workers and message broker
    workers: 4344

message registry:
  # Message types that the manager process can send and their meanings
  # Don't change this section without making corresponding changes in
  # the nemo_nowcast.manager module of the NEMO_Nowcast package.
  manager:
    ack: message acknowledged
    checklist cleared: system checklist cleared
    unregistered worker: ERROR - message received from unregistered worker
    unregistered message type: ERROR - unregistered message type received from worker
    no after_worker function: ERROR - after_worker function not found in next_workers module

  # Module from which to load :py:func:`after_<worker_name>` functions
  # that provide lists of workers to launch when :kbd:`worker_name` finishes.
  # Use fully qualified, dotted notation.
  next workers module: nowcast.next_workers

  workers:
    # Worker module name
    download_weather:
      # The key in the system checklist that the manager maintains that is to
      # be used to hold message payload information provided by the worker
      checklist key: weather forecast
      # Message types that the worker can send and their meanings
      success 00: 00 weather forecast ready
      failure 00: 00 weather forecast download failed
      success 06: 06 weather forecast ready
      failure 06: 06 weather forecast download failed
      success 12: 12 weather forecast ready
      failure 12: 12 weather forecast download failed
      success 18: 18 weather forecast ready
      failure 18: 18 weather forecast download failed
      crash: download_weather worker crashed
    make_runoff_file:
      checklist key: rivers forcing
      success: rivers forcing ready
      failure: rivers forcing files preparation failed
      crash: make_runoff_file worker crashed
    get_NeahBay_ssh:
      checklist key: Neah Bay ssh
      success nowcast: Neah Bay ssh for nowcast ready
      failure nowcast: Neah Bay sea surface height file prep for nowcast failed
      success forecast: Neah Bay ssh for forecast ready
      failure forecast : Neah Bay sea surface height file prep for forecast failed
      success forecast2: Neah Bay ssh for forecast2 ready
      failure forecast2: Neah Bay sea surface height file prep for forecast2 failed
      crash: get_NeahBay_ssh worker crashed
    grib_to_netcdf:
      checklist key: weather forcing
      success nowcast+: atmospheric nowcast/forecast forcing ready
      failure nowcast+: atmospheric nowcast forcing files preparation failed
      success forecast2: atmospheric forecast2 forcing ready
      failure forecast2: atmospheric forecast2 forcing files preparation failed
      crash: grib_to_netcdf worker crashed
