# conda environment description file for SalishSeaNowcast package
# development environment
#
# Create a conda environment for development, testing, and documentation
# of the SalishSeaCast system with:
#
#    $ conda env create -f SalishSeaNowcast/envs/environment-dev.yaml
#    $ conda activate salishsea-nowcast
#    $ python3 -m pip install --editable NEMO_Nowcast/
#    $ python3 -m pip install --editable moad_tools/
#    $ python3 -m pip install --editable tools/SalishSeaTools/
#    $ python3 -m pip install --editable Reshapr/
#    $ python3 -m pip install --editable pywgrib2_xr/  # use the SalishSeaCast branch
#    $ python3 -m pip install --editable OPPTools/
#    $ python3 -m pip install --editable NEMO-Cmd/
#    $ python3 -m pip install --editable SalishSeaCmd/
#    $ python3 -m pip install --editable FVCOM-Cmd/
#    $ python3 -m pip install --editable SalishSeaNowcast/

name: salishsea-nowcast

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - attrs
  - beautifulsoup4
  - bottleneck
  - cartopy
  - click
  - cliff
  - cmocean
  - coloredlogs
  - Cython  # for pywgrib2_xr
  - dask
  - docutils
  - f90nml
  - feedgen>=0.9.0
  - flox
  - geopandas
  - gfortran  # for pywgrib2_xr
  - gitpython
  - gsw
  - httpx
  - jasper<3  # for libwgrib2
  - lxml
  - mako
  - matplotlib
  - nc-time-axis
  - netcdf4
  - numpy
  - numpy-indexed
  - pandas
  - paramiko
  - pillow
  - pip
  - poppler
  - pygrib
  - pypdf2
  - pyproj
  - pytables
  - python=3.10
  - python-blosc  # for pywgrib2_xr
  - pyyaml
  - pyzmq
  - rasterio
  - requests
  - retrying
  - rich
  - schedule
  - scipy
  - scour
  - sentry-sdk
  - shapely
  - structlog
  - supervisor
  - tenacity
  - utm
  - verboselogs
  - watchdog
  - wurlitzer  # for pywgrib2_xr
  - xarray

  # For coding style, repo QA, and pkg management
  - black
  - hatch
  - pre-commit

  # For unit tests
  - pytest
  - pytest-cov
  - pytest-httpx
  - pytest-randomly
  - pytest-xdist
  - tomli

  # For documentation
  - sphinx
  - sphinx_rtd_theme=1.1.1
  - sphinx-notfound-page

  # For exploration
#  - ipython
#  - jupyter

  - pip:
    - angles
    - python-hglib
    - sysrsync
