# conda environment description file for SalishSeaCast system
# production deployment environment for the sarracenia client that
# maintains mirrors of the HRDPS forecast files and rivers hydrometric
# files from the ECCC MSC datamart service.
#
# Create a conda environment for production deployment
# of the sarracenia client with:
#
#    $ conda env create \
#        -f SalishSeaNowcast/envs/environment-sarracenia.yaml \
#        --prefix /SalishSeaCast/sarracenia-env

name: sarracenia-env

channels:
  - conda-forge
  - nodefaults

dependencies:
  - amqp
  - appdirs
  - humanfriendly
  - humanize
  - jsonpickle
  - netifaces
  - pip
  - psutil
  - paramiko
  - python=3.10
  - watchdog

  - pip:
    - metpx-sarracenia[amqp]

variables:
  SARRACENIA_ENV: /SalishSeaCast/sarracenia-env
  SARRACENIA_CONFIG: /SalishSeaCast/SalishSeaNowcast/sarracenia
