# conda environment description file for SalishSeaNowcast package
# development environment
#
# Create a conda environment for development, testing, and documentation
# of the SalishSeaCast system with:
#
#    $ conda env create -f SalishSeaNowcast/envs/environment-dev.yaml
#    $ source activate salishsea-nowcast
#    $ python3 -m pip install --editable NEMO_Nowcast/
#    $ python3 -m pip install --editable moad_tools/
#    $ python3 -m pip install --editable tools/SalishSeaTools/
#    $ python3 -m pip install --editable OPPTools/
#    $ python3 -m pip install --editable NEMO-Cmd/
#    $ python3 -m pip install --editable SalishSeaCmd/
#    $ python3 -m pip install --editable FVCOM-Cmd/
#    $ python3 -m pip install --editable SalishSeaNowcast/

name: salishsea-nowcast

channels:
  - conda-forge

dependencies:
  - arrow
  - attrs
  - beautifulsoup4
  - bottleneck
  - cartopy
  - cliff
  - cmocean
  - coloredlogs
  - dask
  - docutils
  - f90nml
  - feedgen>=0.9.0
  - geopandas
  - gitpython
  - gsw
  - lxml
  - mako
  - matplotlib>=3
  - nc-time-axis
  - netcdf4
  - numpy
  - numpy-indexed
  - pandas
  - paramiko
  - pillow
  - pip
  - poppler
  - pygrib
  - pypdf2
  - pyproj
  - pytables
  - python=3.9
  - pyyaml
  - pyzmq
  - rasterio
  - requests
  - retrying
  - schedule
  - scipy
  - scour
  - sentry-sdk
  - shapely
  - supervisor
  - utm
  - verboselogs
  - watchdog
  - xarray
  - zeep

  # For coding style
  - black

  # For unit tests
  - coverage
  - pytest
#  If your machine has enough cores & RAM for distributed testing
#  - pytest-xdist

  # For documentation
  - sphinx
  - sphinx_rtd_theme

  # For exploration
#  - ipython
#  - jupyter

  - pip:
    - angles
    - python-hglib

    # For unit tests
    - pytest-randomly
