# conda environment description file for SalishSeaNowcast package
# development environment
#
# Create a conda environment for development, testing, and documentation
# of the SalishSeaCast system with:
#
#    $ conda env create -f SalishSeaNowcast/envs/environment-dev.yaml
#    $ conda activate salishsea-nowcast
#    $ python -m pip install --editable NEMO_Nowcast/
#    $ python -m pip install --editable moad_tools/
#    $ python -m pip install --editable tools/SalishSeaTools/
#    $ python -m pip install --editable Reshapr/
#    $ python -m pip install --editable OPPTools/
#    $ python -m pip install --editable NEMO-Cmd/
#    $ python -m pip install --editable SalishSeaCmd/
#    $ python -m pip install --editable SalishSeaNowcast/

name: salishsea-nowcast

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - attrs
  - beautifulsoup4
  - bottleneck
  - cartopy
  - cfgrib
  - click
  - cliff
  - cmocean
  - coloredlogs
  - dask
  - docutils
  - et_xmlfile
  - f90nml
  - feedgen
  - flox
  - gitpython
  - gsw
  - h5netcdf
  - httpx
  - lxml
  - mako
  - matplotlib
  - nc-time-axis
  - netcdf4
  - numpy
  - numpy-indexed
  - openpyxl
  - pandas
  - paramiko
  - pillow
  - pip
  - poppler
  - pygrib
  - pypdf
  - pyproj
  - python=3.13
  - pyyaml
  - pyzmq
  - requests
  - retrying
  - rich
  - schedule
  - scipy
  - scour
  - sentry-sdk
  - structlog
  - supervisor
  - tenacity
  - tqdm
  - utm
  - verboselogs
  - watchdog
  - xarray=2025.1.1

  # For coding style, repo QA, and pkg management
  - black
  - hatch
  - pre-commit

  # For unit tests
  - pytest
  - pytest-cov
  - pytest-httpx
  - pytest-randomly
  - pytest-xdist
  - tomli

  # For documentation
  - sphinx==8.1.3
  - sphinx-notfound-page==1.0.4
  - sphinx-rtd-theme==3.0.0

  # For exploration
#  - ipython
#  - jupyter

  - pip:
    - angles
    - python-hglib
    - sysrsync
