# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

import os
import sys

sys.path.insert(0, os.path.abspath(".."))


# -- Project information -----------------------------------------------------

import configparser

setup_cfg = configparser.ConfigParser()
setup_cfg.read(os.path.abspath("../setup.cfg"))
project = setup_cfg["metadata"]["name"]

author = "Salish Sea MEOPAR Project Contributors and The University of British Columbia"

import datetime

pkg_creation_year = 2013
copyright_years = (
    f"{pkg_creation_year}"
    if datetime.date.today().year == pkg_creation_year
    else f"{pkg_creation_year}-{datetime.date.today():%Y}"
)
copyright = f"{copyright_years}, {author}"

# The short X.Y version
import nowcast

version = nowcast.__version__
# The full version, including alpha/beta/rc tags
release = version


# -- General configuration ----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.mathjax",
    "sphinx.ext.todo",
    "sphinx.ext.viewcode",
]

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "nemonowcast": ("https://nemo-nowcast.readthedocs.io/en/latest/", None),
    "salishseadocs": ("https://salishsea-meopar-docs.readthedocs.io/en/latest/", None),
    "salishseatools": (
        "https://salishsea-meopar-tools.readthedocs.io/en/latest/",
        None,
    ),
    "salishseasite": ("https://salishsea-site.readthedocs.io/en/latest/", None),
    "salishseacmd": ("https://salishseacmd.readthedocs.io/en/latest/", None),
}

todo_include_todos = True

autodoc_mock_imports = [
    "bs4",
    "cmocean",
    "f90nml",
    "feedgen",
    "feedgen.entry",
    "feedgen.feed",
    "fvcom_cmd",
    "gsw",
    "mako",
    "mako.template",
    "moad_tools",
    "moad_tools.observations",
    "moad_tools.places",
    "mpl_toolkits.basemap",
    "nemo_cmd",
    "nemo_nowcast.fileutils",
    "nemo_nowcast.workers",
    "nemo_nowcast.workers.clear_checklist",
    "nemo_nowcast.workers.rotate_logs",
    "netCDF4",
    "OPPTools",
    "pandas",
    "paramiko",
    "salishsea_cmd",
    "salishsea_cmd.api",
    "salishsea_tools",
    "salishsea_tools.LiveOcean_BCs",
    "salishsea_tools.namelist",
    "salishsea_tools.places",
    "salishsea_tools.UBC_subdomain",
    "salishsea_tools.unit_conversions",
    "scipy",
    "scipy.interpolate",
    "scipy.io",
    "shapely",
    "xarray",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "**.ipynb_checkpoints"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"


# -- Options for HTML output --------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "sphinx_rtd_theme"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "_static/MEOPAR_favicon.ico"

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = "%b %d, %Y"

# If false, no module index is generated.
html_domain_indices = False

# If false, no index is generated.
html_use_index = False

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = True
