# conda environment description file for docs build environment
# on readthedocs.org

name: sphinx-build

channels:
  - defaults
  - gomss-nowcast

dependencies:
  - matplotlib>=3
  - nemo_nowcast
  - python=3.6
  - retrying

  # RTD packages
  - mock
  - pillow
  - sphinx
  - sphinx_rtd_theme
