# conda environment description file for SalishSeaCast web site figures
# development environment
#
# Create a conda environment for web site figures development and testing with:
#
#    $ conda env create -f SalishSeaNowcast/env/environment-fig-dev.yaml
#    $ source activate nowcast-fig-dev
#    $ pip install --editable NEMO_Nowcast/
#    $ pip install --editable moad_tools/
#    $ pip install --editable tools/SalishSeaTools/
#    $ pip install --editable NEMO-Cmd/
#    $ pip install --editable SalishSeaCmd/
#    $ pip install --editable SalishSeaNowcast/
#    $ pip install --editable salishsea-site/

name: nowcast-fig-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - arrow
  - basemap
  - beautifulsoup4
  - bottleneck
  - cliff
  - cmocean
  - coloredlogs
  - dask
  - docutils
  - gitpython
  - gsw
  - lxml
  - mako
  - matplotlib>=3
  - netcdf4
  - numpy
  - pandas
  - paramiko
  - pillow
  - pip
  - poppler
  - pygrib
  - pypdf2
  - pyproj
  - pytables
  - python=3.7
  - pyyaml
  - requests
  - scipy
  - shapely
  - verboselogs
  - watchdog
  - xarray

  # For coding style
  - black

  # For figures development
  - jupyterlab

  # For documentation
  - sphinx
  - sphinx_rtd_theme

  - pip:
    - angles
    - attrs
    - f90nml
    - feedgen
    - pyramid
    - pyramid_crow
    - pyramid_debugtoolbar
    - pyramid_mako
    - python-hglib
    - retrying
    - schedule
    - scour
    - supervisor
    - utm
    - waitress
    - zeep
