name: Add Milestone to Issue/PR

permissions: {}

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  add_milestone:
    name: Add current milestone to issue/PR
    permissions:
      issues: write  # Required to assign milestones to issues
      pull-requests: write  # Required to add milestone to PRs
    uses: UBC-MOAD/gha-workflows/.github/workflows/auto-milestone-issue-pr.yaml@main  # zizmor: ignore[unpinned-uses]
