name: CI

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  test-coverage:
    name: pytest & coverage report
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6']

    steps:
      - uses: actions/checkout@v2

      - uses: goanpeca/setup-miniconda@v1
        with:
           auto-update-conda: true
           auto-activate-base: false
           environment-file: environment-test.yaml
           python-version: ${{ matrix.python-version }}
           activate-environment: salishsea-nowcast-test

      - name: Install package
        shell: bash -l {0}
        run: |
          python3 -m pip install --editable git@github.com:43ravens/NEMO_Nowcast.git#egg=NEMO_Nowcast
