name: pytest-with-coverage

permissions: {}

on:
  push:
    branches: ['*']
  # Enable workflow to be triggered from GitHub CLI, browser, or via API
  # primarily for testing conda env solution for new Python versions
  workflow_dispatch:

# Helps prevent parallel runs of the workflow from overlapping
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pytest-with-coverage:
    name: pytest with coverage
    permissions:
      contents: read  # Required to check out the repo
      pull-requests: write  # Required to comment on pull requests
    strategy:
      fail-fast: false
      matrix:
        # Need to specify the environment in a matrix because that's what the reusable
        # workflow expects
        environment: [ 'test-py314' ]

    uses: UBC-MOAD/gha-workflows/.github/workflows/pixi-pytest-with-coverage.yaml@main  # zizmor: ignore[unpinned-uses]
    with:
      environment: ${{ matrix.environment }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
