name: sphinx-linkcheck

permissions: {}

on:
  push:
    branches: ['*']
  schedule:
    - cron: 43 4 1 * *  # 04:43 UTC on the 1st day of each month

jobs:
  sphinx-linkcheck:
    name: Sphinx linkcheck
    permissions:
      contents: read  # Required to check out the repo

    uses: UBC-MOAD/gha-workflows/.github/workflows/pixi-sphinx-linkcheck.yaml@main  # zizmor: ignore[unpinned-uses]
